blank_issues_enabled: true
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/orgs/marmoos-project/discussions
    about: For questions and general discussions, please use GitHub Discussions
  - name: ðŸ“š Documentation
    url: https://github.com/marmoos-project
    about: Check our documentation for guides and examples
